Multiprocessing logic
NexaAI/nexa-sdk pull request #175
Opened 2024-10-19 00:18 UTC by JoyboyBrian

2024-10-19 00:28 UTC, zhiyuan8 requested changes
Please ask David to test

2024-10-19 00:28 UTC, zhiyuan8 commented on pyproject.toml
> +    "Programming Language :: Python :: 3.13",
please merge main

2024-10-19 00:28 UTC, zhiyuan8 commented on nexa/eval/evaluator.py
> +                rank=0, limit=task_limit, world_size=1
add comments and explain

2024-10-19 00:28 UTC, zhiyuan8 commented on nexa/eval/evaluator.py
> +                idx, resp = result_queue.get(timeout=1)
what is queue.get() fails or timeout?

2024-10-19 00:28 UTC, zhiyuan8 commented on nexa/eval/evaluator.py
> +            rank=0,
add explanations here

2024-10-19 00:28 UTC, zhiyuan8 commented on nexa/eval/evaluator.py
> +            # Print error to stderr (will be suppressed)
please improve this comment

2024-10-19 02:56 UTC, zhiyuan8 approved these changes

2024-10-21 06:08 UTC, JoyboyBrian commented
Windows Issue 
```bash
Traceback (most recent call last):
  File "C:\nexa-sdk\nexa-sdk\nexa\gguf\nexa_inference_text.py", line 116, in _load_model
    self.model = Llama(
  File "C:\nexa-sdk\nexa-sdk\nexa\gguf\llama\llama.py", line 364, in __init__
    _LlamaModel(
  File "C:\nexa-sdk\nexa-sdk\nexa\gguf\llama\_internals_transformers.py", line 50, in __init__
    self.model = llama_cpp.llama_load_model_from_file(
OSError: exception: access violation reading 0x0000000000000000
2024-10-20:21:35:32,909 ERROR    [nexa_eval.py:145] An error occurred during evaluation: exception: access violation reading 0x0000000000000000
```

2024-10-22 04:26 UTC, Davidqian123 approved these changes

2024-10-22 04:28 UTC, merged