Qingying model router streamlit
NexaAI/nexa-sdk pull request #201
Opened 2024-10-31 21:36 UTC by qmeng222

Integrated the model router into all model types (NLP, Vision, Multimodal, and Audio) in Streamlit.

2024-10-31 21:48 UTC, unseenmars commented
@zhiyuan8 This is the step one of the model router for Streamlit interface.

2024-11-02 18:31 UTC, zhiyuan8 requested changes

2024-11-02 18:31 UTC, zhiyuan8 commented on nexa/gguf/streamlit/streamlit_image_chat.py
> +    "num_inference_steps": 50,
50 steps is too slow, and lcm-dreamshaper only takes 4 steps, sd1.5 takes 20 steps
https://github.com/NexaAI/nexa-sdk/blob/main/nexa/gguf/nexa_inference_image.py#L176

also, image generation parameters are predefined here
https://github.com/NexaAI/nexa-sdk/blob/main/nexa/constants.py#L286-L320

2024-11-02 18:38 UTC, zhiyuan8 requested changes
same functions are copied multiple times, need code refactoring.

2024-11-02 18:38 UTC, zhiyuan8 commented on nexa/gguf/streamlit/streamlit_image_chat.py
> +def parse_nexa_list_output() -> List[str]:
why not directly get add a helper funciton here? running "nexa list" with string parsing is not a good practice

https://github.com/NexaAI/nexa-sdk/blob/6b30851fdbe6e263531778e15638a283cd4ed5c1/nexa/general.py#L510-L517

2024-11-02 18:38 UTC, zhiyuan8 commented on nexa/gguf/streamlit/streamlit_vlm.py
> +def parse_nexa_list_output() -> List[str]:
same issue, do not parse string
also for general functions, put them in utils.py and import, do not copy code blocks multiple times.

2024-11-02 18:38 UTC, zhiyuan8 commented on nexa/gguf/streamlit/streamlit_vlm.py
> +def get_model_options() -> List[str]:
same, do not hard copy the same function multiple places

2024-11-02 18:38 UTC, zhiyuan8 commented on nexa/gguf/streamlit/streamlit_vlm.py
> +def update_model_options():
same, do not hard copy the same function multiple places

2024-11-02 18:38 UTC, zhiyuan8 commented on nexa/gguf/streamlit/streamlit_image_chat.py
> +def update_model_options():
same issue, no hard copy

2024-11-07 02:24 UTC, closed without merging